# http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml
development: &default
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  <<: *default
test:
  <<: *default
